const topics = ['Main page', 'Actions', 'Animals', 'Clothes', 'Emotions', 'Colours', 'Fruits', 'Vegetables', 'Body parts', 'Statistics'];
const cardsCategories = ['Actions', 'Animals', 'Clothes', 'Emotions', 'Colours', 'Fruits', 'Vegetables', 'BodyParts'];

const cards = {
    Actions: [
        {
            word: 'cry',
            translation: 'плакать',
            image: '../assets/img/cry.jpg',
            audioSrc: '../assets/audio/cry.mp3',
        },
        {
            word: 'dance',
            translation: 'танцевать',
            image: '../assets/img/dance.jpg',
            audioSrc: '../assets/audio/dance.mp3',
        },
        {
            word: 'dive',
            translation: 'нырять',
            image: '../assets/img/dive.jpg',
            audioSrc: '../assets/audio/dive.mp3',
        },
        {
            word: 'draw',
            translation: 'рисовать',
            image: '../assets/img/draw.jpg',
            audioSrc: '../assets/audio/draw.mp3',
        },
        {
            word: 'fish',
            translation: 'ловить рыбу',
            image: '../assets/img/fish.jpg',
            audioSrc: '../assets/audio/fish.mp3',
        },
        {
            word: 'fly',
            translation: 'летать',
            image: '../assets/img/fly.jpg',
            audioSrc: '../assets/audio/fly.mp3',
        },
        {
            word: 'hug',
            translation: 'обнимать',
            image: '../assets/img/hug.jpg',
            audioSrc: '../assets/audio/hug.mp3',
        },
        {
            word: 'jump',
            translation: 'прыгать',
            image: '../assets/img/jump.jpg',
            audioSrc: '../assets/audio/jump.mp3',
        },
    ],
    Animals: [
        {
            word: 'cat',
            translation: 'кот',
            image: '../assets/img/cat.jpg',
            audioSrc: '../assets/audio/cat.mp3',
        },
        {
            word: 'chick',
            translation: 'цыплёнок',
            image: '../assets/img/chick.jpg',
            audioSrc: '../assets/audio/chick.mp3',
        },
        {
            word: 'chicken',
            translation: 'курица',
            image: '../assets/img/chicken.jpg',
            audioSrc: '../assets/audio/chicken.mp3',
        },
        {
            word: 'dog',
            translation: 'собака',
            image: '../assets/img/dog.jpg',
            audioSrc: '../assets/audio/dog.mp3',
        },
        {
            word: 'horse',
            translation: 'лошадь',
            image: '../assets/img/horse.jpg',
            audioSrc: '../assets/audio/horse.mp3',
        },
        {
            word: 'pig',
            translation: 'свинья',
            image: '../assets/img/pig.jpg',
            audioSrc: '../assets/audio/pig.mp3',
        },
        {
            word: 'rabbit',
            translation: 'кролик',
            image: '../assets/img/rabbit.jpg',
            audioSrc: '../assets/audio/rabbit.mp3',
        },
        {
            word: 'sheep',
            translation: 'овца',
            image: '../assets/img/sheep.jpg',
            audioSrc: '../assets/audio/sheep.mp3',
        },
    ],
    Clothes: [
        {
            word: 'skirt',
            translation: 'юбка',
            image: '../assets/img/skirt.jpg',
            audioSrc: '../assets/audio/skirt.mp3',
        },
        {
            word: 'pants',
            translation: 'брюки',
            image: '../assets/img/pants.jpg',
            audioSrc: '../assets/audio/pants.mp3',
        },
        {
            word: 'blouse',
            translation: 'блузка',
            image: '../assets/img/blouse.jpg',
            audioSrc: '../assets/audio/blouse.mp3',
        },
        {
            word: 'dress',
            translation: 'платье',
            image: '../assets/img/dress.jpg',
            audioSrc: '../assets/audio/dress.mp3',
        },
        {
            word: 'boot',
            translation: 'ботинок',
            image: '../assets/img/boot.jpg',
            audioSrc: '../assets/audio/boot.mp3',
        },
        {
            word: 'shirt',
            translation: 'рубашка',
            image: '../assets/img/shirt.jpg',
            audioSrc: '../assets/audio/shirt.mp3',
        },
        {
            word: 'coat',
            translation: 'пальто',
            image: '../assets/img/coat.jpg',
            audioSrc: '../assets/audio/coat.mp3',
        },
        {
            word: 'shoe',
            translation: 'туфли',
            image: '../assets/img/shoe.jpg',
            audioSrc: '../assets/audio/shoe.mp3',
        },
    ],
    Emotions: [
        {
            word: 'sad',
            translation: 'грустный',
            image: '../assets/img/sad.jpg',
            audioSrc: '../assets/audio/sad.mp3',
        },
        {
            word: 'angry',
            translation: 'сердитый',
            image: '../assets/img/angry.jpg',
            audioSrc: '../assets/audio/angry.mp3',
        },
        {
            word: 'happy',
            translation: 'счастливый',
            image: '../assets/img/happy.jpg',
            audioSrc: '../assets/audio/happy.mp3',
        },
        {
            word: 'tired',
            translation: 'уставший',
            image: '../assets/img/tired.jpg',
            audioSrc: '../assets/audio/tired.mp3',
        },
        {
            word: 'surprised',
            translation: 'удивлённый',
            image: '../assets/img/surprised.jpg',
            audioSrc: '../assets/audio/surprised.mp3',
        },
        {
            word: 'scared',
            translation: 'испуганный',
            image: '../assets/img/scared.jpg',
            audioSrc: '../assets/audio/scared.mp3',
        },
        {
            word: 'smile',
            translation: 'улыбка',
            image: '../assets/img/smile.jpg',
            audioSrc: '../assets/audio/smile.mp3',
        },
        {
            word: 'laugh',
            translation: 'смех',
            image: '../assets/img/laugh.jpg',
            audioSrc: '../assets/audio/laugh.mp3',
        },
    ],
    Colours: [
        {
            word: 'brown',
            translation: 'коричневый',
            image: '../assets/img/brown.jpg',
            audioSrc: '../assets/audio/brown.wav',
        },
        {
            word: 'yellow',
            translation: 'жёлтый',
            image: '../assets/img/yellow.jpg',
            audioSrc: '../assets/audio/yellow.wav',
        },
        {
            word: 'orange',
            translation: 'оранжевый',
            image: '../assets/img/orange.jpg',
            audioSrc: '../assets/audio/orange.wav',
        },
        {
            word: 'red',
            translation: 'красный',
            image: '../assets/img/red.jpg',
            audioSrc: '../assets/audio/red.wav',
        },
        {
            word: 'green',
            translation: 'зелёный',
            image: '../assets/img/green.jpg',
            audioSrc: '../assets/audio/green.wav',
        },
        {
            word: 'blue',
            translation: 'голубой',
            image: '../assets/img/blue.jpg',
            audioSrc: '../assets/audio/blue.wav',
        },
        {
            word: 'purple',
            translation: 'фиолетовый',
            image: '../assets/img/purple.jpg',
            audioSrc: '../assets/audio/purple.wav',
        },
        {
            word: 'black',
            translation: 'чёрный',
            image: '../assets/img/black.jpg',
            audioSrc: '../assets/audio/black.wav',
        },
    ],
    Fruits: [
        {
            word: 'apple',
            translation: 'яблоко',
            image: '../assets/img/apple.jpg',
            audioSrc: '../assets/audio/apple.wav',
        },
        {
            word: 'banana',
            translation: 'банан',
            image: '../assets/img/banana.jpg',
            audioSrc: '../assets/audio/banana.wav',
        },
        {
            word: 'orange',
            translation: 'апельсин',
            image: '../assets/img/orange1.jpg',
            audioSrc: '../assets/audio/orange1.wav',
        },
        {
            word: 'peach',
            translation: 'персик',
            image: '../assets/img/peach.jpg',
            audioSrc: '../assets/audio/peach.wav',
        },
        {
            word: 'grape',
            translation: 'виноград',
            image: '../assets/img/grape.jpg',
            audioSrc: '../assets/audio/grape.wav',
        },
        {
            word: 'cherry',
            translation: 'вишня',
            image: '../assets/img/cherry.jpg',
            audioSrc: '../assets/audio/cherry.wav',
        },
        {
            word: 'plum',
            translation: 'слива',
            image: '../assets/img/plum.jpg',
            audioSrc: '../assets/audio/plum.wav',
        },
        {
            word: 'strawberry',
            translation: 'клубника',
            image: '../assets/img/strawberry.jpg',
            audioSrc: '../assets/audio/strawberry.wav',
        },
    ],
    Vegetables: [
        {
            word: 'cucumber',
            translation: 'огурец',
            image: '../assets/img/cucumber.jpg',
            audioSrc: '../assets/audio/cucumber.wav',
        },
        {
            word: 'pepper',
            translation: 'перец',
            image: '../assets/img/pepper.jpg',
            audioSrc: '../assets/audio/pepper.wav',
        },
        {
            word: 'tomato',
            translation: 'помидор',
            image: '../assets/img/tomato.jpg',
            audioSrc: '../assets/audio/tomato.wav',
        },
        {
            word: 'onion',
            translation: 'лук',
            image: '../assets/img/onion.jpg',
            audioSrc: '../assets/audio/onion.wav',
        },
        {
            word: 'cabbage',
            translation: 'капуста',
            image: '../assets/img/cabbage.jpg',
            audioSrc: '../assets/audio/cabbage.wav',
        },
        {
            word: 'carrot',
            translation: 'морковь',
            image: '../assets/img/carrot.jpg',
            audioSrc: '../assets/audio/carrot.wav',
        },
        {
            word: 'mushroom',
            translation: 'гриб',
            image: '../assets/img/mushroom.jpg',
            audioSrc: '../assets/audio/mushroom.wav',
        },
        {
            word: 'corn',
            translation: 'кукуруза',
            image: '../assets/img/corn.jpg',
            audioSrc: '../assets/audio/corn.wav',
        },
    ],
    BodyParts: [
        {
            word: 'head',
            translation: 'голова',
            image: '../assets/img/head.jpg',
            audioSrc: '../assets/audio/head.wav',
        },
        {
            word: 'foot',
            translation: 'нога',
            image: '../assets/img/foot.jpg',
            audioSrc: '../assets/audio/foot.wav',
        },
        {
            word: 'hair',
            translation: 'волосы',
            image: '../assets/img/hair.jpg',
            audioSrc: '../assets/audio/hair.wav',
        },
        {
            word: 'nose',
            translation: 'нос',
            image: '../assets/img/nose.jpg',
            audioSrc: '../assets/audio/nose.wav',
        },
        {
            word: 'mouth',
            translation: 'рот',
            image: '../assets/img/mouth.jpg',
            audioSrc: '../assets/audio/mouth.wav',
        },
        {
            word: 'hand',
            translation: 'рука',
            image: '../assets/img/hand.jpg',
            audioSrc: '../assets/audio/hand.wav',
        },
        {
            word: 'ear',
            translation: 'ухо',
            image: '../assets/img/ear.jpg',
            audioSrc: '../assets/audio/ear.wav',
        },
        {
            word: 'eye',
            translation: 'глаз',
            image: '../assets/img/eye.jpg',
            audioSrc: '../assets/audio/eye.wav',
        },
    ],
};

export  { cards, topics, cardsCategories };
